# Generated by Django 2.2.6 on 2020-03-12 20:41

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20200309_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=video.models.user_directory_path),
        ),
    ]
